### ISSUE TITLE
Log files

### ISSUE THREAD

**Issue by mabelzhang** [osrf/mbari_wec_gz#114]
Replicate csv log files from physical buoy system.

On the physical system, filenames and folders are specific to the time of day. Think about the best way to do this for a faster-than-real-time simulated system.
hamilton8415: "Perhaps it's as simple as each simulation start creates a new logfile directory with a name specific to the start-time, then the filenames proceed forward from there representing simulation time."

Assign to rhenthorn upon agreement

**Comment by rhenthorn** [comment]
As long as the data messages contain simulation time there should not be an issue.

**Comment by rhenthorn** [comment]
I have begun working on this issue. Created henthorn/sim_pblog branch in buoy_msgs repo.

Used the python controller template as a starting point for this node - handy as the template controller subscribes to all the topics needed.

**Comment by andermi** [comment]
@rhenthorn would you please add a launch argument (to controller.launch.py or whatever you may have changed the name to) to specify a custom log directory?

**Comment by rhenthorn** [comment]
The node sim_pblog has been added to buoy_msgs repo branch 'henthorn/sim_pblog'. Some items to resolve:

1. Add a custom log folder as a launch argument
2. First field 'epoch seconds' in the log file (use simulation time - starts at 0.0, or add sim time to current epoch seconds?)
3. Integrate into buoy_gazebo to launch sim_pblog with the simulation

Thanks everyone for your help and patience.

**Comment by rhenthorn** [comment]
Also add to items to resolve

1. insert dependencies in packages.xml

**Comment by andermi** [comment]
If you wouldn't mind starting a PR in the buoy_msgs repo, we could start reviewing :)

**Comment by mabelzhang** [comment]
PR https://github.com/osrf/buoy_msgs/pull/44
