### ISSUE TITLE
`launch_pc_commands_ros_feedback.launch.py` Timeout

### ISSUE THREAD

**Issue by andermi** [osrf/mbari_wec_gz#117]
For some reason this test still intermittently times out:
`35 - launch_pc_commands_ros_feedback.launch.py (Failed)`

Opening a ticket to keep track of this.

**Comment by mabelzhang** [comment]
Linking to the PR where the flakiness was discovered: #111

**Comment by mabelzhang** [comment]
(Maybe) Fixed in #120
Reopen if comes back

**Comment by andermi** [comment]
Still a problem in #125

**Comment by andermi** [comment]
https://github.com/osrf/buoy_sim/pull/125#discussion_r1086163958

**Comment by mabelzhang** [comment]
Latest: Currently temporarily bandaged on `main` by testing until pass. But that means CI will run for a long time. Flakiness is temporarily solved. Test failure should still be fixed.

**Comment by andermi** [comment]
Haven't seen the issue in a while
