### ISSUE TITLE
CI failing to detect 'ros-humble-actuator-msgs'

### ISSUE THREAD

**Issue by quarkytale** [osrf/mbari_wec_gz#142]
All PRs on this repo are stuck on this error, even seeing the same while building the docker image on `mbari_wec`.

```
  apt: command [apt-get install -y ros-humble-actuator-msgs] failed
  apt: Failed to detect successful installation of [ros-humble-actuator-msgs]
Error: Process completed with exit code 1.
```

**Comment by quarkytale** [comment]
> I guess it needs a port to humble? (edited)

Seems like its already added, https://github.com/ros/rosdistro/pull/36795

**Comment by andermi** [comment]
well, somehow it didn't make it into apt after that

**Comment by andermi** [comment]
at the very least, we aren't using anything related to the actuator_msgs stuff so I'm fine reverting and freezing ros_gz for now. We can just tie that commit to our release

**Comment by andermi** [comment]
something like this: https://github.com/osrf/mbari_wec/pull/51

**Comment by quarkytale** [comment]
Adding ros-testing sources list fixes our build, this is a temporary fix till a Humble sync is out (by this week).

**Comment by andermi** [comment]
Please see my comment in #143

**Comment by quarkytale** [comment]
Tested this after Humble sync, apt install worked and could build the latest `ros2` branch of `ros_gz` too!
